[package]
name = "image2emblem"
version = "0.1.0"
authors = ["Ricardo Mendes <rokusu@gmail.com>"]

[dependencies]
byteorder = "0.3.9"
getopts = "0.2"
argparse = "*"
clap = "*"
image = "0.3.11"
time = "0.1"
chrono = "0.2"
